### PR TITLE
Deal with // in URLs

### PR DESCRIPTION
**Pull request by maeve-fpf**
### Status

Closes https://github.com/freedomofpress/infrastructure/issues/3425

We are getting requests that include `/https-everywhere//`. The default behavior of nginx is to merge multiple slashes and serve the page anyway. Because we want to purge Cloudflare by individual URL, this is undesirable. Instead, redirect anything without exactly 1 slash to the canonical `/https-everywhere/`.

This also includes removal of the `application/octet-stream` MIME type, which has been tested in the `https-everywhere-2021` branch's container for a while with no ill effects.

### Review Checklist

No changes to ruleset itself or not-included-in-the-container files.

Locally, run `make serve` and check http://127.0.0.1:4080/ .

This should be checked thoroughly on staging before merge-and-deploy-to-prod. To do so I will:

- Build and push container image manually
- Update k8s image tag for staging only and PR there

### Post-Deployment Checklist

Verify redirect behavior again with both `curl` and the extension. Unfortunately I don't think it's possible to verify that Cloudflare purging happens if the ruleset itself has no changes.

### CODE REVIEW

**Review by ketudb — DISMISSED** [review]
> Locally, run make serve and check http://127.0.0.1:4080/ .

Bearing in mind I'm using podman instead of docker locally, this worked great, and it all seems good. I'm going to approve, but not merge, given the extra caution you suggested around the testing of this.

**Comment by maeve-fpf** [comment]
Marking as draft until Thursday; I will do staging testing tomorrow.

**Comment by ketudb** [comment]
Last comment notes that you were marking this as draft - is it now ready for review?

**Comment by maeve-fpf** [comment]
@ketudb yes, this should now be ready.

**Review by ketudb — APPROVED** [review]

**Pull request merged**
