### PR TITLE
Add Forbidden Stories to ruleset

### PR DESCRIPTION
**Pull request by rocodes**
### Status

Work in Progress - requires signing

### Review Checklist

- [x] Changes to `onboarded.txt` are accurate
- [x] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [x] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [x] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

### CODE REVIEW

**Comment by zenmonkeykstop** [comment]
Signature added, ready for review.

**Review by eloquence — APPROVED** [review]

**Comment by eloquence** [comment]
All LGTM, thank you both :)

**Comment by eloquence** [comment]
There appear to be still some issues with cache invalidation for these ruleset updates, so not ticking the final box just yet.

**Comment by eloquence** [comment]
Cache fully invalidated, directory updated.

**Pull request merged**
