### PR TITLE
Add TechCrunch to ruleset

### PR DESCRIPTION
**Pull request by rocodes**
### Status

WIP (requires signing & timestamp) 

### Review Checklist

- [x] Changes to `onboarded.txt` are accurate
- [x] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [x] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/rocodes/securedrop-https-everywhere-ruleset/techcrunch`
- [x] `index.html` has been updated using `./update_index.sh`

### CODE REVIEW

**Comment by conorsch** [comment]
@rocodes I've signed and pushed. Can you perform a functionality verification of the changes in Tor Browser, using the testing instructions from https://github.com/freedomofpress/securedrop-https-everywhere-ruleset/pull/19#issuecomment-741446348 ? Assuming you can confirm the functionality, we can ping another maintainer for a +1 and permit merge to prod.

**Comment by zenmonkeykstop** [comment]
As per earlier, I'm grabbing this for verification purposes

**Comment by zenmonkeykstop** [comment]
With the added update  channel pulling from `rocodes/techcrunch`, behaves as expected. Doing rest of review now.

**Review by zenmonkeykstop — APPROVED** [review]
Checklist passes, this is good to go!

**Comment by conorsch** [comment]
Thanks, @zenmonkeykstop! I manually busted the cache on this endpoint, so the latest data should be live in prod. That is, you should be able to use it in Tor Browser, with no testing update channels, effective immediately.

**Comment by rocodes** [comment]
@conorsch Apologies if I am misunderstanding, but I am not seeing this ruleset addition live.

**Comment by conorsch** [comment]
@rocodes You were correct, the changes weren't yet live in prod. They are now, though, and I'm seeing the new TC redirect work in Tor Browser on my end, with no testing channels in place. Give it another try to confirm.

**Comment by rocodes** [comment]
Success! Thank you for the speedy resolution @conorsch!

**Pull request merged**
