### PR TITLE
Backports addition of Forbidden Stories

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
### Status

Ready for review:

- add Forbidden Stories to ruleset
-  update Torstar address
- include cherry-picked changes to nginx config from #59

Signed with 2021 key, currently only supported by [TBB Alpha](https://www.torproject.org/download/alpha/)

### Review Checklist

- [x] Changes to `onboarded.txt` are accurate
- [x] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [x] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a 10.5+ Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [x] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

### CODE REVIEW

**Comment by maeve-fpf** [comment]
nginx changes look good! If it's at all helpful, I rebased `nginx-fixes` on `060948a` (Forbidden Stories), so if someone wants to rebase on the latter they can drop my commits and `merge` them back in without the `[TEST] ` junk in the commit message.

**Comment by zenmonkeykstop** [comment]
Tried this out in the latest alpha, rule changes show up - if @eloquence or someone else can take a look it would be good to get it merged on the off-chance the alpha period goes really quickly :)

**Comment by eloquence** [comment]
I've got an alpha ready, will give it a spin.

**Comment by eloquence** [comment]
Starting with the GitHub URL, of course I'm hitting the issue again where all onion sites break after I change the Path Prefix - though "rulesets version" correctly set to `2021.6.30`

**Comment by eloquence** [comment]
OK, after troubleshooting with Kev, determined that the trick appears to be to wait a fairly significant time (up to ~1 minute) after adding the Path Prefix before trying an onion name again - the resolution of the ruleset date does _not_ indicate that it's ready to use.

**Review by eloquence — APPROVED** [review]
All looks good once it actually loaded.

**Pull request merged**
