### PR TITLE
Add FT onion name

### LINKED ISSUE #73: Add FT entry
FT's SecureDrop is back in the directory:

https://securedrop.org/directory/financial-times/

They've requested the onion name `ft.securedrop.tor.onion`.

### PR DESCRIPTION
**Pull request by conorsch**
### Status

Ready for review

Closes #73

### Review Checklist

- [ ] Changes to `onboarded.txt` are accurate
- [ ] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [ ] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [ ] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

### CODE REVIEW

**Comment by eloquence** [comment]
:x: The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to Path Prefix: https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME

Unfortunately this part doesn't work for me. This is likely entirely unrelated to the PR - I've always found Tor Browser very finicky when it comes to configuring the dev ruleset. It usually requires a browser restart as well as a couple of minutes delay. But even with multiple restarts it doesn't work for me this time around -- onion names are just completely borked after I make the change to https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/73-let-there-be-ft, with or without the `/` at the end.

It's possible that my extension is now in an unrecoverable state and I'll have to try with a fresh browser install - but I'd appreciate if someone else could take a spin. Given how fragile HTTPSE is in this respect, we may want to document the exact step a bit more clearly in the PR template.

**Comment by zenmonkeykstop** [comment]
I'll review now.

**Comment by zenmonkeykstop** [comment]
Seeing the same behavior, with the added wrinkle that even after changing back to the `https://securedrop.org/https-everywhere-2021/` prefix, onion names stay b0rked.

**Comment by eloquence** [comment]
Yeah, same here. Possible that our test workflow is no longer supported :/

**Comment by zenmonkeykstop** [comment]
works when going from default to a previous branch's ruleset (tested the add-aj-2021 branch specifically) - but that's the same ruleset as is in the default right now so it may just not have refreshed anything!

**Comment by zenmonkeykstop** [comment]
Oh, never mind, it's working for me now.

**Review by zenmonkeykstop — APPROVED** [review]
- [x] Changes to onboarded.txt are accurate
- [x] The file default.rulesets.TIMESTAMP.gz has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [x] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to Path Prefix: https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME **Note: this was hard to verify. https-everywhere seems to have some flakiness wrt ruleset updates and replacements.**
- [x] index.html has been updated using ./update_index.sh

LGTM

**Pull request merged**
