### PR TITLE
Adds apache and 2600

### LINKED ISSUE #37: Add onion name for Apache.be
- Onion address: See landing page https://www.apache.be/securedrop/
- v3 enabled: yes
- Directory entry: https://securedrop.org/directory/apache/
- Requested onion name: apache.securedrop.tor.onion

### LINKED ISSUE #38: Add onion name for 2600.com
- Onion address: https://www.2600.com/securedrop/
- v3 enabled: yes
- Directory entry: https://securedrop.org/directory/2600-hacker-quarterly/
- Requested onion name: 2600.securedrop.tor.onion

### PR DESCRIPTION
**Pull request by emkll**
### Status
Ready for review

Fixes #37
Fixes #38 

### Review Checklist

- [x] Changes to `onboarded.txt` are accurate
- [x] The file `default.rulesets.TIMESTAMP.gz` has been updated, extracting that file and inspecting the contents of the JSON file produces the expected rules
- [x] The ruleset has been verified by modifying the HTTPS Everywhere configuration in a Tor Browser instance pointing to `Path Prefix`: `https://raw.githubusercontent.com/freedomofpress/securedrop-https-everywhere-ruleset/$BRANCH_NAME`
- [x] `index.html` has been updated using `./update_index.sh`

### Post-Deployment Checklist

- [ ] Added/modified onion names have been updated in the SecureDrop Directory

### CODE REVIEW

**Comment by conorsch** [comment]
Haven't reviewed yet, post-merge, please monitor for updates to the prod endpoint. They should happen automatically. There may still be a caching delay, but @maeve-fpf (or I) can bust the cache at a moment's notice. I'm more interest in confirming that the automatic updates to the rulesets are deployed upon merge into the main branch here.

**Review by eloquence — APPROVED** [review]
LGTM! Ticked boxes in in PR body.

**Comment by conorsch** [comment]
> please monitor for updates to the prod endpoint

```
$ curl -s https://securedrop.org/https-everywhere/latest-rulesets-timestamp 
1614864041
```

Looks good! Matches the changes presented here.

**Comment by eloquence** [comment]
I'm having difficulty getting Tor Browser to actually fetch the updated rules. Even when `Update last checked` (in the HTTPSE extension preferences -> Update channels) is just a minute ago, the SecureDrop ruleset is stuck at `2021.2.5`. Auto-update is enabled. I've tried in Tails and using a separate Tor Browser instance on Ubuntu.

`curl`ing the resources at first glance everything looks good, so I'm not sure what's going wrong here. Could you see if you can reproduce?

**Comment by conorsch** [comment]
Could indeed reproduce! `curl` was showing me the latest, but Tor Browser wasn't. That endpoint is heavily cached because it gets a few million hits a day, so I busted the cache manually. After some fussing with Tor Browser where it wouldn't respond to the "Update channel" button in the HTTPSE extension settings, I restarted Tor Browser, and it worked just fine.

So we still need to wire up some automatic cache busting for these changes, but can confirm that the logic was at least deployed. Cache would have expired in ~2h, but we can make it automatic on changes, too.

**Comment by eloquence** [comment]
Confirmed working for me now as well; updated directory entries with onion names. :tada:

**Pull request merged**
